import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { EvidenceTable } from "../shared/EvidenceTable.jsx";
import { PlotLayout } from "../shared/PlotLayout.jsx";
import { ChartLegend } from "../shared/ChartLegend.jsx";
import { NoiseProfilePlot } from "../plots/NoiseProfilePlot.jsx";
import { CC, FF, FW, OBS, CS } from "../../constants/tokens.js";
import { makeRowMapper } from "../shared/coordinates.js";
import { SUB_HEAD, BLOCK_GAP, BLOCK_GAP_TIGHT } from "../shared/styles.js";


export function MiniCard_LOESS({ result, importConfig, rowMap }) {
  // Coordinate mapping
  const { fileRow, toFileRow } = makeRowMapper(importConfig, rowMap);

  const cpRow = result.changepointRow;
  const hasCP = cpRow != null && cpRow !== "—" && String(result.cusumP) !== "—";
  // S243 21b: the changepoint marker reads as a signal, so it gates on the
  // verdict's significance — not on existence of the argmax-CUSUM row. Draw the
  // marker (and its legend swatch) only when a changepoint exists AND the verdict
  // fired, matching the footer / region-table flag gate below.
  const showChangepoint = hasCP && result.flag !== "LOW" && result.flag !== "N/A";
  const regions = result.regionComparison || [];

  // Coordinate-mapped display values
  const cpRowDisplay = hasCP ? toFileRow(cpRow) : null;
  const cpBetween = hasCP ? `between rows ${toFileRow(cpRow - 1)} and ${cpRowDisplay}` : null;
  const bestWinParts = result.bestWindowRows ? String(result.bestWindowRows).match(/(\d+)\D+(\d+)/) : null;
  const bestWinDisplay = bestWinParts
    ? `${toFileRow(parseInt(bestWinParts[1]))}–${toFileRow(parseInt(bestWinParts[2]))}`
    : result.bestWindowRows || "—";

  return (
    <MiniCardLayout result={result}
      footer={result.flag !== "LOW" && result.flag !== "N/A"
        ? (hasCP ? "Noise level changes partway through" : "Noise level varies along the data")
        : "Noise level steady throughout"}
      lookFor={hasCP ? `Noise character changes ${cpBetween}. Compare the data before and after this boundary — do values look smoother, rounder, or more regularly spaced on one side? Check whether the changepoint corresponds to a batch boundary, a date change in the lab notebook, or the point where a different person took over data collection.` : `Rows ${bestWinDisplay} have different noise than the rest. Examine those rows for signs of smoothing (values too round), extrapolation (overly regular spacing), or manual editing. Compare against the original instrument files if available.`}
      implications={`A shift in noise character partway through the dataset can result from a change in experimental conditions — a new reagent batch, instrument recalibration, or a gap between data collection sessions. It can also indicate that one section of the data was generated by a different process from the rest.${hasCP ? ` The changepoint ${cpBetween} marks where the transition occurs.` : ""}`}>

      {result.noiseProfile?.length > 0 && <>
        {/* S210 (multi-surface): primary-surface heading dropped — the footer
            fragment (LEAD_HEAD in MiniCardLayout) heads this primary plot. */}
        <PlotLayout>
          <NoiseProfilePlot noiseProfile={result.noiseProfile}
            changepointRow={showChangepoint ? cpRow : null}
            secondaryRow={result.secondaryRow || null}
            toFileRow={toFileRow}/>
        </PlotLayout>
        <ChartLegend items={[
          { color: CC.OBS, label: "Row noise", opacity: OBS.line.strokeOpacity, swatchType: "line", strokeWidth: CS.DATA.w },
          { color: CC.OBS, label: "LOESS trend", opacity: OBS.line.strokeOpacity, swatchType: "line", strokeWidth: CS.FIT.w, showDot: false },
          ...(showChangepoint ? [{ color: CC.THRESH, label: "Changepoint", swatchType: "line" }] : []),
        ]} />
      </>}
      {regions.length > 0 && result.flag !== "LOW" && result.flag !== "N/A" && (
        <div style={{marginTop: BLOCK_GAP}}>
          {/* S210 (multi-surface): secondary-surface heading demoted (Regular weight). */}
          <div style={{...SUB_HEAD, fontWeight: FW.NORM, marginBottom: BLOCK_GAP_TIGHT}}>Region comparison</div>
          <EvidenceTable
            columns={["Region", "Rows", "Observed SD", "Expected SD", "Ratio", "Finding"]}
            identifierColumns={2}
            rows={regions.map(r => {
              // Map rows to file coordinates
              const rowParts = String(r.rows).match(/(\d+)\D+(\d+)/);
              const rowsDisplay = rowParts
                ? `${toFileRow(parseInt(rowParts[1]))}–${toFileRow(parseInt(rowParts[2]))}`
                : r.rows;
              return [
                { value: r.region, style: { fontFamily: FF.UI } },
                rowsDisplay,
                r.observedNoise,
                r.expectedNoise,
                r.ratio,
                { value: r.finding, style: { fontFamily: FF.UI } },
              ];
            })}
          />
        </div>
      )}

    </MiniCardLayout>
  );
}
