import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { PlotLayout } from "../shared/PlotLayout.jsx";
import { ChartLegend } from "../shared/ChartLegend.jsx";
import { VBarPlot } from "../plots/VBarPlot.jsx";
import { CC } from "../../constants/tokens.js";


export function MiniCard_Benford({ result, importConfig, rowMap }) {
  const details = result.details || [];
  const name = result.name;
if(!details.length) return null;
const isSecond = name.includes("Second");
const items=details.map(d=>({...d,
  expNum:parseFloat(d.benfordPct)||0,
  obsNum:parseFloat(d.observedPct)||0}));
return (

  <MiniCardLayout result={result}
    footer={result.flag !== "LOW" && result.flag !== "N/A"
      ? (isSecond ? "Second digits depart from the expected pattern" : "Leading digits depart from the expected pattern")
      : (isSecond ? "Second digits as expected" : "Leading digits as expected")}
    lookFor={isSecond ? "Look for excess 0s and 5s (rounding signature) or deficit of certain digits. Second-digit Benford is most powerful for detecting fabrication in large datasets — small deviations become significant with enough data." : "Check whether smaller digits (1–3) are depleted or larger digits (7–9) are inflated compared to Benford's law. This pattern suggests values were chosen from a narrow range or generated uniformly rather than arising from natural processes." }
    implications={isSecond
      ? "As with first digits, second-digit deviations can arise from narrow-range or bounded-scale data. Second-digit analysis can also catch subtler patterns that first-digit analysis misses — the second-digit distribution is less widely known and less likely to be corrected if values have been manually adjusted."
      : "Departure from the Benford distribution can occur in data with a narrow measurement range or bounded scales, where the expected digit pattern does not apply. It can also indicate values that were not generated by a natural multiplicative process — for example, numbers chosen or constructed rather than measured."}>

    {/* S210 (single-surface): section heading dropped — the footer
        fragment (LEAD_HEAD in MiniCardLayout) heads this sole plot. */}
    <PlotLayout>
        <VBarPlot
          items={items}
          xKey="digit" obsKey="obsNum"
          expKey="expNum"
          obsColor={CC.OBS}
          expColor={CC.EXP}
          xlabel={isSecond ? "Second digit (0–9)" : "Leading digit (1–9)"}
          ylabel="Frequency (%)" flag={result.flag}/>
    </PlotLayout>
    <ChartLegend items={[
      { color: CC.OBS, label: "Observed %", opacity: 0.35 },
      { color: CC.EXP, label: "Benford expected", swatchType: "line" },
    ]} />


  </MiniCardLayout>

);

}
