/* ── MiniCard: Column Goodness-of-Fit ──
   Mirrors MiniCard_Entropy structure: per-flagged-column DataTable +
   footer. Producer (src/tests/columnGof.js) emits
   `details: [{Col, Family, Direction, A2_obs, A2_null_median, Ratio,
   adjP}]` for flagged columns; this card surfaces it.

   S126b add-9: created to fill the empty-card-body gap surfaced by
   DS11 verification. Pre-add-9 there was no entry for "Column
   Goodness-of-Fit" in MINIPLOT_REGISTRY (MiniPlot.jsx) so the test
   card body rendered nothing under the title + verdict badge. */

import { C, FS, FF } from "../../constants/tokens.js";
import { fmtP } from "../../constants/thresholds.js";
import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { DataTable } from "../shared/DataTable.jsx";
import { EvidenceTable } from "../shared/EvidenceTable.jsx";
import { SUB_HEAD } from "../shared/styles.js";
import { ColumnStatBar } from "../plots/ColumnStatBar.jsx";

// Family slugs come from the producer in lowercase ("normal" / "poisson"
// / "nb"). Render with their conventional statistics formatting.
const FAMILY_LABEL = {
  normal: "Normal",
  poisson: "Poisson",
  nb: "Negative Binomial",
};

// Convert producer's Direction + family into a user-facing finding
// string. Mirrors MiniCard_Entropy's Direction → text mapping.
function findingText(direction, family) {
  const fam = FAMILY_LABEL[family] || family;
  if (direction === "Shape mismatch") {
    return `Doesn't fit ${fam}`;
  }
  if (direction === "Too-tight fit") {
    return `Fits ${fam} too tightly`;
  }
  return direction;
}

export function MiniCard_ColumnGoF({ result, importConfig, rowMap }) {
  const nFlagged = result.nFlagged || 0;
  const nHigh = result.nHigh || 0;
  const nLow = result.nLow || 0;

  const flaggedColLabels = (result.details || [])
    .map(d => `Col ${d.Col}`)
    .filter(Boolean);
  const flaggedColStr = flaggedColLabels.length
    ? flaggedColLabels.join(", ")
    : "flagged columns";

  const implications = nHigh > 0 && nLow === 0
    ? `Values in ${flaggedColStr} don't match the reference distribution shape predicted from their mean and variance — heavier-tailed, multi-peaked, or otherwise off-shape compared to the {Normal, Poisson, Negative Binomial} family they should follow. This can result from mixing values from genuinely different sources, copy-paste from a different distribution, or hand-typed values that introduce shape distortion. Examine the column histograms for unusual heavy/light tails or multi-modal structure.`
    : nLow > 0 && nHigh === 0
    ? `Values in ${flaggedColStr} fit their reference distribution TOO closely — closer than typical measurement noise produces. This can result from values being generated by a random number process (e.g. RNG-padded fabrication) where the synthetic noise matches the assumed family by construction, rather than from real instrument readings.`
    : `Some columns deviate from their reference distribution shape (too heavy/multimodal/skewed) while others fit too closely (suspect of synthetic generation). Mixed pattern can result from combining data from different sources or from selective fabrication of a subset of columns.`;

  // Per-condition routing path: aggregator rebuilds `details` as the
  // per-group summary (one row per condition), so we bind the table to
  // `subDetails` (per-row evidence flattened across groups, prefixed with
  // `group`) when aggregated. Single-matrix path keeps the existing
  // DataTable. Matches the Mahalanobis generic-subDetails precedent.
  const isAgg = result.groupsAssessed !== undefined;
  const sub = result.subDetails || [];
  const rows = (result.details || []).slice(0, 20);

  // Per-column bar items: all tested columns, flagged + unflagged.
  const barItems = (result.colRatios || []).map(c => ({
    colLabel: `Col ${c.col}`,
    value: c.ratio,
    flagged: !!c.flagged,
  }));
  const skippedItems = (result.skippedColumns || []).map(s => ({
    col: s.col, colLabel: `Col ${s.col}`, reason: s.reason,
  }));

  return (
    <MiniCardLayout result={result}
      footer={nFlagged > 0
        ? (nFlagged === 1
            ? "1 column doesn't fit its expected shape"
            : `${nFlagged} columns don't fit their expected shape`)
        : "all columns fit their expected shape"}
      lookFor="Mismatch columns ('shape doesn't fit') deviate from the reference family — examine their histograms for heavy/light tails, multiple modes, or unusual clustering. Too-tight columns fit suspiciously well: examine for too-regular spacing or values that look generated rather than measured. Both directions warrant cross-checking against the original instrument output."
      implications={implications}>

      {(barItems.length > 0 || skippedItems.length > 0) && (
        <ColumnStatBar items={barItems} skipped={skippedItems} cardFlag={result.flag}
          isAggregated={isAgg}
          refValue={1} refLabel="Null median (ratio = 1)"
          valueAxisLabel="A² ratio"
          skippedClause="near-uniform shape outside the {Normal, Poisson, NB} family (v1.1: LogNormal, Gamma)" />
      )}

      {isAgg && sub.length > 0 && (() => {
        // Aggregated (per-condition) path — render the flat per-row evidence
        // from subDetails with auto-derived columns and a Condition column
        // (group → Condition). Matches MiniCard_Mahalanobis.
        const cols = Object.keys(sub[0]);
        const headerMap = { group: "Condition", adjP: "adj. p", A2_obs: "A²", A2_null_median: "A² null median", Ratio: "A² ratio" };
        const etCols = cols.map(k => ({ label: headerMap[k] || k }));
        const etRows = sub.slice(0, 20).map(row => cols.map(k => {
          if (k === "adjP") return fmtP(row[k]);
          if (k === "Family") return FAMILY_LABEL[row[k]] || row[k];
          return row[k];
        }));
        return (
          <div style={{ marginTop: "8px" }}>
            <div style={SUB_HEAD}>Flagged columns</div>
            <EvidenceTable columns={etCols} rows={etRows} identifierColumns={2} compact />
            {sub.length > 20 && <div style={{ fontFamily: FF.UI, fontSize: FS.xs, color: C.TEXT_3, marginTop: "3px" }}>…and {sub.length - 20} more</div>}
          </div>
        );
      })()}

      {!isAgg && rows.length > 0 && (
        <div style={{ marginTop: "8px" }}>
          <div style={SUB_HEAD}>Flagged columns</div>
          <DataTable data={rows} maxRows={20} compact identifierColumns={2} columns={[
            { header: "Col", bold: true, render: d => d.Col },
            { header: "Finding", render: d => findingText(d.Direction, d.Family) },
            { header: "A² ratio", bold: true, render: d => d.Ratio },
            { header: "adj. p", render: d => fmtP(d.adjP) },
          ]} />
          {nFlagged > 20 && <div style={{ fontFamily: FF.UI, fontSize: FS.xs, color: C.TEXT_3, marginTop: "3px" }}>…and {nFlagged - 20} more</div>}
        </div>
      )}

    </MiniCardLayout>
  );
}
