/* ── MiniCard: Constant Offset ── */

import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { EvidenceTable } from "../shared/EvidenceTable.jsx";
import { buildCondColorMap } from "../../constants/roles.js";
import { makeRowMapper } from "../shared/coordinates.js";

export function MiniCard_ConstantOffset({ result, importConfig, rowMap }) {
  const details = result.details || [];
  const sub = result.subDetails || [];
  const isAgg = result.groupsAssessed !== undefined;
  const condColorMap = buildCondColorMap(importConfig?.condPerCol);
  const condCell = (name) => { const color = condColorMap[name]?.text; return color ? {value: name, style: {color}} : name; };
  // Producer emits 1-indexed matrix rows in d.positions ("35–36"); render
  // file rows so the card matches the §2 highlight's `#` column.
  const { toFileRow } = makeRowMapper(importConfig, rowMap);
  const positionsToFileRows = (s) => {
    const m = String(s).match(/(\d+)\D+(\d+)/);
    return m ? `${toFileRow(parseInt(m[1]))}–${toFileRow(parseInt(m[2]))}` : s;
  };

  // Build block evidence rows from subDetails (multi-cond) or details (single-cond)
  const blockEntries = isAgg
    ? sub.filter(d => d.pair && d.positions)
    : details.filter(d => d.pair && d.positions);
  const hasBlocks = blockEntries.length > 0 && result.flag !== "LOW" && result.flag !== "N/A";

  // Format offset with sign
  const fmtOffset = (d) => {
    if (typeof d === "string" && d.startsWith("×")) return d; // multiplicative
    const v = parseFloat(d);
    if (isNaN(v)) return d;
    return v >= 0 ? `+${v.toFixed(4)}` : v.toFixed(4);
  };

  return (
    <MiniCardLayout result={result}
      footer={result.flag !== "LOW" && result.flag !== "N/A"
        ? `${blockEntries.length} offset cop${blockEntries.length !== 1 ? "ies" : "y"} — block reappears shifted by a constant`
        : "No offset copies found"}
      lookFor="Look at the flagged row pairs in the table — do the offsets form a pattern? If the same offset appears across multiple replicate pairs at the same rows, it suggests those rows were generated by copying one value and adding a constant. Check whether the flagged rows cluster in one region of the dataset or span the whole file."
      implications="A constant difference between replicates over consecutive rows can result from batch corrections or instrument drift adjustments applied uniformly to a block. It can also indicate that one row was copied and a fixed value added or subtracted to create neighbouring rows.">

      {hasBlocks && (
        <div>
          <EvidenceTable
            columns={isAgg ? ["Condition", "Pair", "Rows", "Offset"] : ["Pair", "Rows", "Offset"]}
            rows={blockEntries.map(d => isAgg
              ? [condCell(d.group), d.pair, positionsToFileRows(d.positions), fmtOffset(d.diff)]
              : [d.pair, positionsToFileRows(d.positions), fmtOffset(d.diff)]
            )}
            identifierColumns={isAgg ? 3 : 2}
            footerText={!isAgg && blockEntries.length < result.consecutiveEqualDiffs ? `Showing ${blockEntries.length} of ${result.consecutiveEqualDiffs}.` : undefined}
          />
        </div>
      )}
    </MiniCardLayout>
  );
}
