/* ── MiniCard: Entropy / Zipf Analysis ── */

import { C, TF, FW, FF } from "../../constants/tokens.js";
import { fmtP, fmtPBadge } from "../../constants/thresholds.js";
import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { DataTable } from "../shared/DataTable.jsx";
import { SUB_HEAD } from "../shared/styles.js";


export function MiniCard_Entropy({ result, importConfig, rowMap }) {
  const nFlagged = result.nFlagged || 0;
  const nLow = result.nLow || 0;
  const nHigh = result.nHigh || 0;

  const flaggedCols = (result.details || []).filter(d => d.flag === "HIGH" || d.flag === "MODERATE").map(d => d.column || d.col).filter(Boolean);
  const flaggedColStr = flaggedCols.length ? flaggedCols.join(", ") : "flagged columns";
  const entropyImplications = nLow > 0 && nHigh === 0
    ? `Values in ${flaggedColStr} repeat more than the column distribution predicts — fewer distinct values appear than expected. This can result from instrument resolution limits or aggressive rounding. It can also indicate values drawn from a restricted repertoire rather than measured independently.`
    : nHigh > 0 && nLow === 0
    ? `Values in ${flaggedColStr} are spread more evenly than the column distribution predicts — more distinct values with more uniform spacing than typical measurements produce. This can result from high-precision instruments with fine resolution. It can also indicate values generated by a random number process rather than recorded from an instrument.`
    : `Some columns show too few distinct values (low entropy) while others show too many (high entropy). This mixed pattern can result from combining data from different sources. It can also indicate that some columns were measured and others were constructed.`;

  // Plain-English headline
  let headline;
  if (result.flag === "LOW" || result.flag === "N/A") {
    headline = "Value entropy is consistent with expected distributions — no columns show anomalous diversity.";
  } else if (nLow > 0 && nHigh === 0) {
    headline = `${nLow} column${nLow !== 1 ? "s have" : " has"} unusually low entropy — fewer distinct values than expected.`;
  } else if (nHigh > 0 && nLow === 0) {
    headline = `${nHigh} column${nHigh !== 1 ? "s have" : " has"} unusually high entropy — more uniformly distributed than expected.`;
  } else {
    headline = `${nFlagged} columns with anomalous entropy: ${nLow} low (too few values), ${nHigh} high (too uniform).`;
  }

  // Details table (flagged columns)
  const rows = (result.details || []).slice(0, 20);

  return (
    <MiniCardLayout result={result} headline={headline}
      desc={result.description}
      footer={<>
        {result.nTested} column{result.nTested !== 1 ? "s" : ""} tested
        {" · "}{nFlagged} flagged ({nLow} low, {nHigh} high)
        {result.fewColumnsNote && ` · ${result.fewColumnsNote}`}
        {" · " + fmtPBadge(result.primaryP)}
      </>}
      lookFor="Low-entropy columns suggest values were drawn from a restricted set — too few distinct values for what's expected. High-entropy columns suggest over-randomisation — values were spread too uniformly to look 'real'. Check whether flagged columns correspond to key results or treatment groups."
      implications={entropyImplications}>

      {rows.length > 0 && (
        <div style={{ marginTop: "8px" }}>
          <div style={SUB_HEAD}>Flagged columns</div>
          <DataTable data={rows} maxRows={20} compact identifierColumns={2} columns={[
            { header: "Col", bold: true, render: d => d.Col },
            { header: "Finding", render: d => d.Direction === "Low entropy" ? "Too few distinct values" : d.Direction === "High entropy" ? "Too many distinct values" : d.Direction },
            { header: "Excess", bold: true, render: d => { const r = parseFloat(d.Ratio); if (isNaN(r)) return d.Ratio; const pct = Math.round((r - 1) * 100); return (pct >= 0 ? "+" : "") + pct + "%"; } },
            { header: "adj. p", render: d => fmtP(d.adjP) },
          ]} />
          {nFlagged > 20 && <div style={{ fontFamily: FF.UI, fontSize: TF.DETAIL, color: C.TEXT_4, marginTop: "3px" }}>…and {nFlagged - 20} more</div>}
        </div>
      )}

    </MiniCardLayout>
  );
}
