/* ── MiniCard: Within-Row Variance ── */

import { C, CC, TF, FW, FF, SIGNAL } from "../../constants/tokens.js";
import { fmtPOp } from "../../constants/thresholds.js";
import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { EvidenceTable } from "../shared/EvidenceTable.jsx";
import { PlotLayout } from "../shared/PlotLayout.jsx";

import { ChartLegend } from "../shared/ChartLegend.jsx";
import { PlotSVG } from "../plots/PlotSVG.jsx";
import { SUB_HEAD } from "../shared/styles.js";

export function MiniCard_WithinRowVariance({ result, importConfig, rowMap }) {
  const nOut = result.nOutliers || 0;
  const nSmooth = (result.flaggedRows || []).filter(r => r.direction === "too smooth").length;
  const nNoisy = nOut - nSmooth;

  // Z-score histogram
  const zScores = result.zScores || [];
  let histPlot = null;
  if (zScores.length > 10) {
    const bins = 40;
    const zMin = Math.min(-5, Math.min(...zScores));
    const zMax = Math.max(5, Math.max(...zScores));
    const binW = (zMax - zMin) / bins;
    const counts = new Array(bins).fill(0);
    for (const z of zScores) {
      const bi = Math.min(bins - 1, Math.max(0, Math.floor((z - zMin) / binW)));
      counts[bi]++;
    }
    const maxC = Math.max(...counts, 1);
    const W = 280, H = 80, padL = 2, padR = 2, padT = 2, padB = 14;
    const plotW = W - padL - padR, plotH = H - padT - padB;
    const barW = plotW / bins;

    histPlot = (
      <PlotSVG width={W} height={H} style={{ display: "block", margin: "4px auto" }}>
        {counts.map((c, i) => {
          const x = padL + i * barW;
          const h = (c / maxC) * plotH;
          const zMid = zMin + (i + 0.5) * binW;
          const isOutlier = Math.abs(zMid) > 3.5;
          const fill = isOutlier ? SIGNAL.RED.dot : C.TEXT_4;
          return <rect key={i} x={x} y={padT + plotH - h} width={barW - 0.5} height={h}
            fill={fill} fillOpacity="0.35" stroke={fill} strokeWidth="1" />;
        })}
        {/* Threshold lines at ±3.5 */}
        {[-3.5, 3.5].map(z => {
          const x = padL + ((z - zMin) / (zMax - zMin)) * plotW;
          return x > padL && x < W - padR ? (
            <line key={z} x1={x} y1={padT} x2={x} y2={padT + plotH}
              stroke={SIGNAL.RED.dot} strokeWidth={1} strokeDasharray="3,2" opacity={0.7} />
          ) : null;
        })}
        {/* Labels */}
        <text x={padL + plotW / 2} y={H - 1} textAnchor="middle" fontSize={9} fill={C.TEXT_4}>z-score (SD vs expected)</text>
      </PlotSVG>
    );
  }

  // Details table
  const rows = (result.details || []).slice(0, 20);

  return (
    <MiniCardLayout result={result}
      footer={<>
        {result.nValid||"?"} rows tested · {nOut} outlier{nOut !== 1 ? "s" : ""} ({nSmooth} smooth, {nNoisy} noisy) · expected {result.expectedOutliers}
        {" · global p\u202f" + fmtPOp(parseFloat(result.globalP))}
        {result.windowSigCount > 0 && ` · ${result.windowSigCount} sig. window${result.windowSigCount !== 1 ? "s" : ""}`}
      </>}
      lookFor="Look at the 'too smooth' rows — do they cluster in one region, or correspond to key results? If someone fabricated a row by typing a value and adding small noise, the within-row SD will be much lower than expected for that mean level. Check whether smooth rows correspond to the conditions with the most dramatic claimed effects."
      implications={`${nSmooth || "Some"} row${nSmooth !== 1 ? "s" : ""} show${nSmooth === 1 ? "s" : ""} replicates that agree more closely than the overall noise pattern predicts for their signal level. Unusually uniform replicates can result from natural low-variance features or from values that were generated by starting from a target and adding small perturbations rather than recording independent measurements.`}>

      {histPlot && <>
        <PlotLayout>
          {histPlot}
        </PlotLayout>
        <ChartLegend items={[
          { color: SIGNAL.RED.dot, label: "Outside ±3.5σ threshold", opacity: 0.35 },
          { color: C.TEXT_4, label: "Within expected range", opacity: 0.35 },
        ]} />
      </>}

      {rows.length > 0 && (
        <div style={{ marginTop: "8px" }}>
          <div style={SUB_HEAD}>Outlier rows</div>
          <EvidenceTable
            columns={[{label:"Row"},{label:"z"},{label:"Direction"},{label:"SD"},{label:"Expected"}]}
            identifierColumns={1}
            compact
            rows={rows.slice(0,20).map(d => [
              {value: d.Row, style:{fontWeight:FW.BOLD}},
              {value: d.z, style:{fontWeight:FW.BOLD}},
              {value: d.Direction, style:{fontFamily:FF.UI}},
              d.SD,
              d.Expected,
            ])}
            footerText={nOut > 20 ? `Showing 20 of ${nOut}.` : undefined}
          />
        </div>
      )}

    </MiniCardLayout>
  );
}
