/* ── MiniCard: Column Goodness-of-Fit ──
   Mirrors MiniCard_Entropy structure: per-flagged-column DataTable +
   footer. Producer (src/tests/columnGof.js) emits
   `details: [{Col, Family, Direction, A2_obs, A2_null_median, Ratio,
   adjP}]` for flagged columns; this card surfaces it.

   S126b add-9: created to fill the empty-card-body gap surfaced by
   DS11 verification. Pre-add-9 there was no entry for "Column
   Goodness-of-Fit" in MINIPLOT_REGISTRY (MiniPlot.jsx) so the test
   card body rendered nothing under the title + verdict badge. */

import { C, TF, FS, FF } from "../../constants/tokens.js";
import { fmtP, fmtPBadge } from "../../constants/thresholds.js";
import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { DataTable } from "../shared/DataTable.jsx";
import { SUB_HEAD } from "../shared/styles.js";

// Family slugs come from the producer in lowercase ("normal" / "poisson"
// / "nb"). Render with their conventional statistics formatting.
const FAMILY_LABEL = {
  normal: "Normal",
  poisson: "Poisson",
  nb: "Negative Binomial",
};

// Convert producer's Direction + family into a user-facing finding
// string. Mirrors MiniCard_Entropy's Direction → text mapping.
function findingText(direction, family) {
  const fam = FAMILY_LABEL[family] || family;
  if (direction === "Shape mismatch") {
    return `Doesn't fit ${fam}`;
  }
  if (direction === "Too-tight fit") {
    return `Fits ${fam} too tightly`;
  }
  return direction;
}

export function MiniCard_ColumnGoF({ result, importConfig, rowMap }) {
  const nFlagged = result.nFlagged || 0;
  const nHigh = result.nHigh || 0;
  const nLow = result.nLow || 0;

  const flaggedColLabels = (result.details || [])
    .map(d => `Col ${d.Col}`)
    .filter(Boolean);
  const flaggedColStr = flaggedColLabels.length
    ? flaggedColLabels.join(", ")
    : "flagged columns";

  const implications = nHigh > 0 && nLow === 0
    ? `Values in ${flaggedColStr} don't match the reference distribution shape predicted from their mean and variance — heavier-tailed, multi-peaked, or otherwise off-shape compared to the {Normal, Poisson, Negative Binomial} family they should follow. This can result from mixing values from genuinely different sources, copy-paste from a different distribution, or hand-typed values that introduce shape distortion. Examine the column histograms for unusual heavy/light tails or multi-modal structure.`
    : nLow > 0 && nHigh === 0
    ? `Values in ${flaggedColStr} fit their reference distribution TOO closely — closer than typical measurement noise produces. This can result from values being generated by a random number process (e.g. RNG-padded fabrication) where the synthetic noise matches the assumed family by construction, rather than from real instrument readings.`
    : `Some columns deviate from their reference distribution shape (too heavy/multimodal/skewed) while others fit too closely (suspect of synthetic generation). Mixed pattern can result from combining data from different sources or from selective fabrication of a subset of columns.`;

  // Details table (flagged columns)
  const rows = (result.details || []).slice(0, 20);

  return (
    <MiniCardLayout result={result}
      footer={<>
        {result.nTested} column{result.nTested !== 1 ? "s" : ""} tested
        {" · "}{nFlagged} flagged ({nHigh} mismatch, {nLow} too-tight)
        {result.fewColumnsNote && ` · ${result.fewColumnsNote}`}
        {" · " + fmtPBadge(result.primaryP)}
      </>}
      lookFor="Mismatch columns ('shape doesn't fit') deviate from the reference family — examine their histograms for heavy/light tails, multiple modes, or unusual clustering. Too-tight columns fit suspiciously well: examine for too-regular spacing or values that look generated rather than measured. Both directions warrant cross-checking against the original instrument output."
      implications={implications}>

      {rows.length > 0 && (
        <div style={{ marginTop: "8px" }}>
          <div style={SUB_HEAD}>Flagged columns</div>
          <DataTable data={rows} maxRows={20} compact identifierColumns={2} columns={[
            { header: "Col", bold: true, render: d => d.Col },
            { header: "Finding", render: d => findingText(d.Direction, d.Family) },
            { header: "A² ratio", bold: true, render: d => d.Ratio },
            { header: "adj. p", render: d => fmtP(d.adjP) },
          ]} />
          {nFlagged > 20 && <div style={{ fontFamily: FF.UI, fontSize: FS.xs, color: C.TEXT_3, marginTop: "3px" }}>…and {nFlagged - 20} more</div>}
        </div>
      )}

    </MiniCardLayout>
  );
}
