/* ── MiniCard: Entropy / Zipf Analysis ── */

import { C, FS, FW, FF } from "../../constants/tokens.js";
import { fmtP } from "../../constants/thresholds.js";
import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { DataTable } from "../shared/DataTable.jsx";
import { EvidenceTable } from "../shared/EvidenceTable.jsx";
import { SUB_HEAD, BLOCK_GAP, BLOCK_GAP_TIGHT } from "../shared/styles.js";
import { ColumnStatBar } from "../plots/ColumnStatBar.jsx";


export function MiniCard_Entropy({ result, importConfig, rowMap }) {
  const nFlagged = result.nFlagged || 0;
  const nLow = result.nLow || 0;
  const nHigh = result.nHigh || 0;

  const flaggedCols = (result.details || []).filter(d => d.flag === "HIGH" || d.flag === "MODERATE").map(d => d.column || d.col).filter(Boolean);
  const flaggedColStr = flaggedCols.length ? flaggedCols.join(", ") : "flagged columns";
  const entropyImplications = nLow > 0 && nHigh === 0
    ? `Values in ${flaggedColStr} repeat more than the column distribution predicts — fewer distinct values appear than expected. This can result from instrument resolution limits or aggressive rounding. It can also indicate values drawn from a restricted repertoire rather than measured independently.`
    : nHigh > 0 && nLow === 0
    ? `Values in ${flaggedColStr} are spread more evenly than the column distribution predicts — more distinct values with more uniform spacing than typical measurements produce. This can result from high-precision instruments with fine resolution. It can also indicate values generated by a random number process rather than recorded from an instrument.`
    : `Some columns show too few distinct values (low entropy) while others show too many (high entropy). This mixed pattern can result from combining data from different sources. It can also indicate that some columns were measured and others were constructed.`;

  // Per-condition routing path: aggregator rebuilds `details` as the
  // per-group summary, so we bind the table to `subDetails` (per-row
  // evidence, prefixed with `group`) when aggregated. Single-matrix path
  // keeps the existing DataTable. Matches MiniCard_Mahalanobis.
  // Entropy producer does not emit `skippedColumns`; the bar's skipped
  // surface stays empty for this card.
  const isAgg = result.groupsAssessed !== undefined;
  const sub = result.subDetails || [];
  const rows = (result.details || []).slice(0, 20);

  // Per-column bar items: all tested columns, flagged + unflagged.
  const barItems = (result.colRatios || []).map(c => ({
    colLabel: `Col ${c.col}`,
    value: c.ratio,
    flagged: !!c.flagged,
  }));

  return (
    <MiniCardLayout result={result}
      footer={nFlagged > 0
        ? (nFlagged === 1
            ? "1 column has too few or too many distinct numbers"
            : `${nFlagged} columns have too few or too many distinct numbers`)
        : "value variety normal across columns"}
      lookFor="Low-entropy columns suggest values were drawn from a restricted set — too few distinct values for what's expected. High-entropy columns suggest over-randomisation — values were spread too uniformly to look 'real'. Check whether flagged columns correspond to key results or treatment groups."
      implications={entropyImplications}>

      {barItems.length > 0 && (
        <ColumnStatBar items={barItems} cardFlag={result.flag}
          isAggregated={isAgg}
          refValue={1} refLabel="Expected (ratio = 1)"
          valueAxisLabel="Entropy ratio" />
      )}

      {isAgg && sub.length > 0 && (() => {
        const cols = Object.keys(sub[0]);
        const headerMap = { group: "Condition", adjP: "adj. p", H_obs: "H", H_expected: "H expected", Ratio: "Ratio" };
        const etCols = cols.map(k => ({ label: headerMap[k] || k }));
        const etRows = sub.slice(0, 20).map(row => cols.map(k => {
          if (k === "adjP") return fmtP(row[k]);
          return row[k];
        }));
        return (
          <div style={{ marginTop: BLOCK_GAP }}>
            {/* S210 (multi-surface): secondary-surface heading kept but demoted
                (Regular weight) to read clearly below the footer-lead. */}
            <div style={{...SUB_HEAD, fontWeight: FW.NORM, marginBottom: BLOCK_GAP_TIGHT}}>Flagged columns</div>
            <EvidenceTable columns={etCols} rows={etRows} identifierColumns={2} compact />
            {sub.length > 20 && <div style={{ fontFamily: FF.UI, fontSize: FS.xs, color: C.TEXT_3, marginTop: "3px" }}>…and {sub.length - 20} more</div>}
          </div>
        );
      })()}

      {!isAgg && rows.length > 0 && (
        <div style={{ marginTop: BLOCK_GAP }}>
          {/* S210 (multi-surface): secondary-surface heading kept but demoted
              (Regular weight) to read clearly below the footer-lead. */}
          <div style={{...SUB_HEAD, fontWeight: FW.NORM, marginBottom: BLOCK_GAP_TIGHT}}>Flagged columns</div>
          <DataTable data={rows} maxRows={20} compact identifierColumns={2} columns={[
            { header: "Col", bold: true, render: d => d.Col },
            { header: "Finding", render: d => d.Direction === "Low entropy" ? "Too few distinct values" : d.Direction === "High entropy" ? "Too many distinct values" : d.Direction },
            { header: "Excess", bold: true, render: d => { const r = parseFloat(d.Ratio); if (isNaN(r)) return d.Ratio; const pct = Math.round((r - 1) * 100); return (pct >= 0 ? "+" : "") + pct + "%"; } },
            { header: "adj. p", render: d => fmtP(d.adjP) },
          ]} />
          {nFlagged > 20 && <div style={{ fontFamily: FF.UI, fontSize: FS.xs, color: C.TEXT_3, marginTop: "3px" }}>…and {nFlagged - 20} more</div>}
        </div>
      )}

    </MiniCardLayout>
  );
}
