import { MiniCardLayout } from "../shared/CardLayout.jsx";
import { PlotLayout } from "../shared/PlotLayout.jsx";
import { ChartLegend } from "../shared/ChartLegend.jsx";
import { VBarPlot } from "../plots/VBarPlot.jsx";
import { C, TF, FW, FF, CC } from "../../constants/tokens.js";
import { fmtPBadge } from "../../constants/thresholds.js";
import { SUB_HEAD } from "../shared/styles.js";


export function MiniCard_Benford({ result, importConfig, rowMap }) {
  const details = result.details || [];
  const sub = result.subDetails || [];
  const name = result.name;
  const isAgg = result.groupsAssessed !== undefined;
if(!details.length) return null;
const isSecond = name.includes("Second");
const items=details.map(d=>({...d,
  expNum:parseFloat(d.benfordPct)||0,
  obsNum:parseFloat(d.observedPct)||0}));
let headline;
if (result.flag === "LOW") {
  headline = isSecond
    ? "Second digits follow the expected Benford distribution."
    : "First digits follow Benford's law — consistent with naturally occurring data.";
} else {
  const worst = [...items].sort((a,b) => Math.abs(b.obsNum - b.expNum) - Math.abs(a.obsNum - a.expNum))[0];
  headline = worst
    ? `Digit ${worst.digit} appears at ${worst.obsNum.toFixed(1)}% (Benford predicts ${worst.expNum.toFixed(1)}%) — ${isSecond ? "second" : "first"} digits deviate from the expected distribution.`
    : `${isSecond ? "Second" : "First"} digits deviate from the expected Benford distribution.`;
}
const desc = isSecond
  ? "Second digits in real measurement data follow a near-uniform distribution with a slight Benford skew. Fabricated data often shows preferences for certain second digits — especially 0 and 5 from rounding."
  : "In naturally occurring datasets, the first significant digit is not equally likely — smaller digits (1, 2, 3) appear more often than larger ones, following Benford's law. Fabricated data tends to be too uniform or shows unusual digit preferences.";
return (

  <MiniCardLayout result={result} headline={headline}
    desc={desc}
    footer={<>
      {result.nValues||"?"} values tested · χ²={result.chiSquared||"?"} · df={result.df||"?"} · {fmtPBadge(result.primaryP)}
    </>}
    lookFor={isSecond ? "Look for excess 0s and 5s (rounding signature) or deficit of certain digits. Second-digit Benford is most powerful for detecting fabrication in large datasets — small deviations become significant with enough data." : "Check whether smaller digits (1–3) are depleted or larger digits (7–9) are inflated compared to Benford's law. This pattern suggests values were chosen from a narrow range or generated uniformly rather than arising from natural processes." }
    implications={isSecond
      ? "As with first digits, second-digit deviations can arise from narrow-range or bounded-scale data. Second-digit analysis can also catch subtler patterns that first-digit analysis misses — the second-digit distribution is less widely known and less likely to be corrected if values have been manually adjusted."
      : "Departure from the Benford distribution can occur in data with a narrow measurement range or bounded scales, where the expected digit pattern does not apply. It can also indicate values that were not generated by a natural multiplicative process — for example, numbers chosen or constructed rather than measured."}>

    <div style={SUB_HEAD}>{isSecond ? "Second digit frequencies" : "Leading digit frequencies"}</div>
    <PlotLayout>
        <VBarPlot
          items={items}
          xKey="digit" obsKey="obsNum"
          expKey="expNum"
          obsColor={CC.OBS}
          expColor={CC.EXP}
          xlabel={isSecond ? "Second digit (0–9)" : "Leading digit (1–9)"}
          ylabel="Frequency (%)"/>
    </PlotLayout>
    <ChartLegend items={[
      { color: CC.OBS, label: "Observed %", opacity: 0.35 },
      { color: CC.EXP, label: "Benford expected", swatchType: "line" },
    ]} />


  </MiniCardLayout>

);

}
