/* ── MiniCard: Rank Correlation ── */

import { C, FW, FF } from "../../constants/tokens.js";
import { TIER_COLOR, cellTextOn } from "../shared/heatmapColors.js";
import { buildCondColorMap } from "../../constants/roles.js";
import { MiniCardLayout, CardBanner } from "../shared/CardLayout.jsx";
import { CorrMatrixSVG } from "../plots/CorrMatrixSVG.jsx";
import { PlotLayout } from "../shared/PlotLayout.jsx";
import { ChartLegend } from "../shared/ChartLegend.jsx";

export function MiniCard_RankCorrelation({ result, importConfig, rowMap }) {
  const details = result.details || [];
  if (!details.length) return null;

  const nPairs = result.nConditionPairs || details.length;

  // ── Build condition names and ρ lookup from pair details ──
  const condColorMap = buildCondColorMap(importConfig?.condPerCol);
  const nameSet = new Set();
  const lookup = {};
  for (const d of details) {
    const parts = d.pair.split(" vs ");
    if (parts.length === 2) {
      const a = parts[0].trim(), b = parts[1].trim();
      nameSet.add(a);
      nameSet.add(b);
      const rho = parseFloat(d.spearmanR);
      lookup[a + "|" + b] = { rho, suspicious: !!d.suspicious };
      lookup[b + "|" + a] = { rho, suspicious: !!d.suspicious };
    }
  }
  const condNames = [...nameSet];
  const hasMatrix = condNames.length >= 2;
  const labelColors = condNames.map(cn => condColorMap[cn]?.text || null);

  // ── Cell colouring — two tiers: Expected / Elevated ──
  const cellBg = (val) => {
    if (!val) return C.BORDER_L;
    return val.suspicious ? TIER_COLOR.MID : TIER_COLOR.LOW;
  };
  const cellTxt = (val) => cellTextOn(cellBg(val));
  const cellBold = (val) => !!val?.suspicious;

  // ── Legend ──
  const legendItems = [
    { color: TIER_COLOR.LOW, label: "Expected" },
    { color: TIER_COLOR.MID, label: "Suspicious" },
  ];

  // ── Footer ── cleared branch added (S209): the test returns LOW
  // (rankCorrelation.js flagRankCap maps LOW→LOW), so the card can render
  // in a non-flagged state.
  const footer = (result.flag !== "LOW" && result.flag !== "N/A")
    ? "Conditions rank their rows more alike than typical"
    : "Conditions rank their rows as expected";


  return (
    <MiniCardLayout result={result}
      footer={footer}
      lookFor="If a pair of conditions that should produce different biological responses has ρ near 1.0, the data for one condition may have been generated by perturbing the other. Check whether the flagged pair corresponds to treatment vs control. Cross-reference with Mahalanobis outlier rows — if the same rows appear as multivariate outliers, the evidence converges."
      implications="Conditions whose row-level patterns rank in the same order can reflect genuine biological similarity — for example, a treatment with a small effect that preserves the underlying sample ranking. Unusually high similarity across multiple condition pairs, however, is difficult to explain biologically when conditions are expected to produce distinct effects.">

      {result.insufficientPairs && (
        <CardBanner type="warn">
          <strong>Informational only</strong> — {nPairs} condition pair{nPairs > 1 ? "s" : ""} is insufficient for statistical inference.
          High ρ between 2 conditions is expected when most features are non-differentially expressed.
        </CardBanner>
      )}

      {hasMatrix && (
        <>
          {/* S210 (single-surface): section heading dropped — the footer
              fragment (LEAD_HEAD in MiniCardLayout) heads this sole surface. */}
          <PlotLayout fitContent>
            <CorrMatrixSVG
              labels={condNames}
              getValue={(rowL, colL) => lookup[rowL + "|" + colL] || null}
              formatCell={val => val ? val.rho.toFixed(2) : ""}
              cellBg={cellBg}
              cellText={cellTxt}
              cellBold={cellBold}
              labelColors={labelColors}
            />
          </PlotLayout>
          <ChartLegend items={legendItems} />
        </>
      )}

    </MiniCardLayout>
  );
}
